services:
  # Option 1: Separate Services (Recommended)
  # Backend API Server
  - type: web
    name: clouddice-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    buildFilter:
      paths:
        - server/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Static Site
  - type: static
    name: clouddice-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://clouddice-server.onrender.com

  # Option 2: Single Docker Container (Alternative)
  # Uncomment below and comment above for Docker deployment
  # - type: web
  #   name: clouddice-docker
  #   env: docker
  #   plan: free
  #   dockerfilePath: ./Dockerfile
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: PORT
  #       value: 10000
